### ISSUE TITLE
[TRACKER] Reorganize/cleanup code

### ISSUE THREAD

**Issue by unho** [Softcatala/translation-memory-tools#13]
- [x] Translate comments in Catalan to English (#30)
- [ ] Add license (#35)
- [x] Softcatalà has a grave accent (so à not á) (#68)
- [ ] Add docs (#14)
- [ ] Include building docs on Travis (#69)
- [ ] Include run of integration tests on Travis (#70)
- [ ] Remove specific references in code to jmas home (and stuff like this) (#56)
- [x] Move images to `img/` directory (#9)
- [x] Move CSS files to `css/` directory (#10)
- [x] Move templates to `templates/` directory (#11)
- [ ] Move SoftCatalá specifics out of repo (#27)
- [ ] Move all tests code to `tests/` directory (#31)
- [x] Perform a cleaning sweep on all the code to ensure we have valid HTML5 (#48)
- [x] Perform a cleaning sweep on all the code to ensure we have valid CSS (#49)
- [x] Perform a cleaning sweep on all the code to ensure we have Python following agreed coding style (#50)
- [x] Get rid of globals on Python code (#60)
- [ ] Move embedded HTML in Python code to standalone templates (#41)
- [x] Make sure which Python this works on (#43)
- [x] Remove all PO and TMX files that are not used for testing purposes (#44)
- [ ] Move the commands to a `bin/` directory (not having a bunch of `.py` files in `src/`)
- [ ] Make it clear which one is the original files directory, the PO directory, the TMX directory... for the importing process.
- [ ] Discuss about maybe separating in two different repositories the translations retrieval (including the translations retrieval and the TMX and PO compendia creation) from the web query server (including index creation and code for the server).
