### ISSUE TITLE
[TRACKER] Add docs

### ISSUE THREAD

**Issue by unho** [Softcatala/translation-memory-tools#14]
- [ ] Simplify the root README (2 or 3 paragraphs intro, and move the rest to the `docs/` directory) (#51)
- [x] Include this project docs in Read the Docs (#52)
- [ ] Remove all README (or other notes files) in the repository, but the root README (#57)
- [ ] Add docs about how to deploy (#53)
- [ ] Add docs about how to import translations (#54)
- [ ] Add docs about how to help in development (#55)
- [x] Add coding style for Python (#37)
- [x] Add coding style for CSS (#38)
- [x] Add coding style for JavaScript (#39)
- [x] Add coding style for HTML (#40)
- [ ] Add coding style for shell scripts (#8)
